In [51]:
from sklearn import svm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

def svm_model(dataSet, testData_persentage, svm_kernel_type, poly_degree):
    img_train, img_test, label_train, label_test = train_test_split(dataSet.data, dataSet.target,test_size=testData_persentage,random_state=0)
    classifier = svm.SVC(kernel = svm_kernel_type, C = 1, gamma = 'auto', degree = poly_degree)
    
    #fitting classifier model
    classifier.fit(img_train, label_train)
    
    # classification_report outputs classification metrics
    # such as precision, recall and F1 score
    pred_result = classifier.predict(img_train)
    print('Classification Training Report: \n', classification_report(label_train, pred_result))
    
    # confusion_matrix outputs how many samples are correctly or incorrectly classified
    print('Train Confusion Matrix: \n', confusion_matrix(label_train, pred_result), "\n")

    # accuracy computes classification accuracy
    print('Train Accuracy: ', accuracy_score(label_train, pred_result))
    print('\n')
    
    # testing with validate data
    validate_result = classifier.predict(img_test)
    print('Classification Testing Report: \n', classification_report(label_test, validate_result))
    # `confusion_matrix` outputs how many samples are correctly or incorrectly classified
    print('Test Confusion Matrix: \n', confusion_matrix(label_test, validate_result), "\n")
    # `accuracy` computes classification accuracy
    print('Test Accuracy: ', accuracy_score(label_test, validate_result))

In [43]:
# example of using svm_model method
# from sklearn import datasets
# from sklearn.utils import Bunch

#load data from .npz file
# npdata = np.load('dataset.npz')

# print(npdata['data'].shape)
# img=np.zeros(shape=(data_number, cropped_window_size ^ 2))
# for i in range(0, data_number): 
#     img[i] = npdata['data'][i].reshape(-1) #flatten image - input data must be 1d-array
# print(img.shape)

# make dataset in Bunch format 
# dataset = Bunch(data = img, target=npdata['label'])

# svm_model(dataset, 0.2, 'rbf', 3)

(2910, 200, 200)
(2910, 40000)
Classification Training Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       686
           1       1.00      1.00      1.00       625
           2       1.00      1.00      1.00      1017

    accuracy                           1.00      2328
   macro avg       1.00      1.00      1.00      2328
weighted avg       1.00      1.00      1.00      2328

Train Confusion Matrix: 
 [[ 686    0    0]
 [   0  625    0]
 [   0    0 1017]] 

Train Accuracy:  1.0


Classification Testing Report: 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       184
           1       0.00      0.00      0.00       158
           2       0.41      1.00      0.58       240

    accuracy                           0.41       582
   macro avg       0.14      0.33      0.19       582
weighted avg       0.17      0.41      0.24       582

Test Confusion Matrix: 
 [[  0   0

D:\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
